services:
  database:
    image: dogmeat2000/database_viatab:latest
    container_name: viatab_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: viatab
    volumes:
      - ./database/viatabloid.sql:/docker-entrypoint-initdb.d/viatabloid.sql:ro
      - pgdata:/var/lib/postgresql/data

  backend:
    image: dogmeat2000/backend_viatab:latest
    container_name: viatab_backend
    depends_on:
      - database
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/viatab
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin

  frontend:
    image: dogmeat2000/frontend_viatab:latest
    container_name: viatab_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      VITE_API_BASE_URL: http://localhost:8080

volumes:
  pgdata:
